export const testimonials = [
    {
      name: "Jessica L.",
      location: "New York, USA",
      rating: 5,
      profileIcon: "https://picsum.photos/id/1011/100/100",
      dataAiHint: "woman portrait",
      timestamp: "2 weeks ago",
      story: "I was skeptical, but my heart was broken. After the 'Reunite Lovers' spell, my ex reached out the very next day. We're talking again and healing. I'm amazed and so grateful!",
    },
    {
      name: "David M.",
      location: "London, UK",
      rating: 5,
      profileIcon: "https://picsum.photos/id/1005/100/100",
      dataAiHint: "man portrait",
      timestamp: "1 month ago",
      story: "The 'Attract New Love' spell worked wonders. I felt a shift in my energy and soon met someone truly special. It felt like destiny. Thank you for opening this new chapter for me.",
    },
    {
      name: "Sophia K.",
      location: "Sydney, Australia",
      rating: 5,
      profileIcon: "https://picsum.photos/id/1027/100/100",
      dataAiHint: "woman face",
      timestamp: "3 days ago",
      story: "There was a third party causing so much pain in my relationship. The 'Strengthen Relationship' spell brought peace and clarity. We're stronger than ever now. Highly recommend.",
    },
    {
      name: "Carlos R.",
      location: "Madrid, Spain",
      rating: 5,
      profileIcon: "https://picsum.photos/id/1012/100/100",
      dataAiHint: "man face",
      timestamp: "5 days ago",
      story: "My marriage was on the verge of divorce. I was desperate. The 'Stop Divorce' spell saved us. It calmed the storms and reminded us of our love. I can't thank you enough.",
    },
    {
      name: "Aisha B.",
      location: "Dubai, UAE",
      rating: 5,
      profileIcon: "https://picsum.photos/id/1013/100/100",
      dataAiHint: "woman smiling",
      timestamp: "1 week ago",
      story: "The financial success spell was unbelievable. I landed a promotion I've been chasing for years and my money situation has completely turned around. This is real magic!",
    },
    {
      name: "Liam O'Connell",
      location: "Dublin, Ireland",
      rating: 5,
      profileIcon: "https://picsum.photos/id/1014/100/100",
      dataAiHint: "irish man",
      timestamp: "3 weeks ago",
      story: "The curse removal was life-changing. I felt a heavy weight lift off my shoulders almost instantly. Opportunities are flowing, and I feel like myself again. Thank you from the bottom of my heart.",
    },
     {
      name: "Isabella Rossi",
      location: "Rome, Italy",
      rating: 5,
      profileIcon: "https://picsum.photos/id/1025/100/100",
      dataAiHint: "italian woman",
      timestamp: "2 months ago",
      story: "After years of trying, the pregnancy spell brought us our miracle. We are expecting our first child. Your guidance and spiritual work have been a true blessing to our family.",
    },
    {
      name: "Kenji Tanaka",
      location: "Tokyo, Japan",
      rating: 5,
      profileIcon: "https://picsum.photos/id/1015/100/100",
      dataAiHint: "japanese man",
      timestamp: "1 month ago",
      story: "The protection spell has given me such peace of mind. The negative energy at my workplace was draining, but now I feel shielded and can focus on my tasks without fear.",
    },
     {
      name: "Fatima Al-Fassi",
      location: "Rabat, Morocco",
      rating: 5,
      profileIcon: "https://picsum.photos/id/1016/100/100",
      dataAiHint: "moroccan woman",
      timestamp: "6 days ago",
      story: "He came back! After two years of no contact, my ex-lover returned just as you said he would. The 'Bring Back Ex Lover' spell is powerful and your guidance was so compassionate.",
    }
  ];
